### ISSUE TITLE
Audio visualizer

### ISSUE THREAD

**Issue by airforce270** [papertek/CyDJ#1]

**Comment by papertek** [comment]
praying everyday for this to be possible

**Comment by papertek** [comment]
test

**Comment by airforce270** [comment]
I don't personally see a way forward on this. I'll release it in case anyone else wants to work on it and/or has ideas on how to approach it.

**Comment by papertek** [comment]
> I don't personally see a way forward on this. I'll release it in case anyone else wants to work on it and/or has ideas on how to approach it.

I would ask vortex but he keeps on donowalling, no clue why but I'll leave it for you to ask him about tampermonkey. You can dm me on dc if I should contact him personally or not. Closing for now

**Comment by papertek** [comment]
reopened for discussion

**Comment by papertek** [comment]
cydj client
