### ISSUE TITLE
Fix media embed when queueing a raw video

### ISSUE THREAD

**Issue by papertek** [papertek/CyDJ#11]
as seen from screenshot the stuff is broken lol
![image](https://user-images.githubusercontent.com/72106503/147532480-b92662a7-2652-4f42-9b2e-e384e7ec4dd4.png)

compare it to vanilla cytube

![image](https://user-images.githubusercontent.com/72106503/147532519-8d8ee934-4fba-4b3d-aed2-65065a28c9f8.png)

**Comment by papertek** [comment]
I looked more into it and it's a bigger problem than I thought,, Mind if u look into this @airforce270 ? It's embedding related

**Comment by airforce270** [comment]
Do you have an example file / url for testing?

**Comment by papertek** [comment]
> Do you have an example file / url for testing?

https://cytu.be/r/testplacelilroc - **Test room with the javascript**

https://cytu.be/r/emptyroomtestplace - **Test room with vanilla CyTube**

[https://vidstreamingcdn.com/cdn12/ff6ab61629ac83bef8833f1e0f77cfe8/EP.1.v0.1639173911.1080p.mp4?mac=n2qhAF3nHgOULLjomLlKNSHJi%2FJtfTEgkv%2FnPrT1Tfg%3D&expiry=1640725275067](url) Raw video link
