### ISSUE TITLE
Multiplication bug

### ISSUE THREAD

**Issue by airforce270** [papertek/CyDJ#17]
When attempting to type `!calc NxN` (ex: `!calc 3x3`, but seems to work with any two numbers), the message fails to send, and the user's next message has `➥` prepended.

The following error is logged to the console:

```
Uncaught SyntaxError: Invalid or unexpected token
    at prepareMessage (main.js?_=1640732859103:1422:24)
    at HTMLInputElement.<anonymous> (main.js?_=1640732859103:4077:10)
    at HTMLInputElement.dispatch (jquery-1.11.0.min.js:3:8066)
    at HTMLInputElement.r.handle (jquery-1.11.0.min.js:3:4767)
```

**Comment by papertek** [comment]
any info on this?

**Comment by airforce270** [comment]
It just passes the input to `eval()` directly so idk.

Honestly using `eval()` is a pretty huge security risk so we should probably just remove `!calc` tbh

**Comment by papertek** [comment]
yeah firetruck calculating

**Comment by papertek** [comment]
Removing calc function once I get home

**Comment by airforce270** [comment]
Removed
