### ISSUE TITLE
Up-arrow message adds empty line to history

### ISSUE THREAD

**Issue by airforce270** [papertek/CyDJ#18]
When using up-arrow to resend a past message, a blank message is added to the message history, i.e.

history:

```
something
blah
asdf
```

user then does up-arrow once to resend `asdf`

new history:

```
something
blah
asdf

asdf
```

So now if the user up-arrows twice, instead of going to `asdf`, it goes to a blank line.

(probably should do neither, I'd think arrowing up twice should go to `blah` even after resending `asdf`)

**Comment by papertek** [comment]
I don't know if this is random or not because it's not happening for me. Unless it's only 3 times specific?

**Comment by airforce270** [comment]
It happens consistently for me regardless of number of messages. You can see the current history by monitoring the `CHATHIST` var:

![image](https://user-images.githubusercontent.com/96109779/147761100-c8c2869d-176e-428d-9e8b-7f0f929db4c7.png)
