### ISSUE TITLE
Persist user stats

### ISSUE THREAD

**Issue by airforce270** [papertek/CyDJ#20]
!stat returns user stats for the current session. Should persist it. 

Only available option is probably local storage (which means the stats will be tied to the browser), but that should be fine. Better than nothing.

**Comment by papertek** [comment]
doesn't that already exist on the footer?

**Comment by airforce270** [comment]
footer only includes visits, !stats includes more:

![](https://cdn.discordapp.com/attachments/534230677269381120/925912048859226163/unknown.png)

**Comment by papertek** [comment]
> footer only includes visits, !stats includes more:
> 
> ![](https://camo.githubusercontent.com/aa16ff7a99def81ec528a949846025a177dd4657191293f820c915782a782b62/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3533343233303637373236393338313132302f3932353931323034383835393232363136332f756e6b6e6f776e2e706e67)

right

**Comment by papertek** [comment]
been fixed for a bit
