### ISSUE TITLE
Fix "playlist options" welcome message for new users

### ISSUE THREAD

**Issue by papertek** [papertek/CyDJ#33]
![image](https://user-images.githubusercontent.com/72106503/147786801-1200f8ba-56e7-4757-8b93-9d41522321be.png)

as seen from the image above the dismiss button on the welcome message doesnt work. i already fixed this but it was lazily fixed by commenting the code. would like to improve

**Comment by papertek** [comment]
best way to reproduce the issue is by using incognito mode on chrome and clearing browsing data **(in incognito mode, not regular chrome)**

![image](https://user-images.githubusercontent.com/72106503/149639814-3419170c-4c3d-4977-bc88-b8f0865726e0.png)

**Comment by airforce270** [comment]
can also run js in console to reset:

`window.localStorage['first_visit'] = 'true';`

**Comment by papertek** [comment]
> can also run js in console to reset:
> 
> `window.localStorage['first_visit'] = 'true';`
![JohnJAM](https://user-images.githubusercontent.com/72106503/149641134-0c7e18cd-e045-4ec1-96be-aa58223893b4.gif)

**Comment by airforce270** [comment]
Fixed by commits in #42
