### ISSUE TITLE
Contributors list not working as intended

### ISSUE THREAD

**Issue by papertek** [papertek/CyDJ#38]
![image](https://user-images.githubusercontent.com/72106503/148129945-931ebacd-67ca-40c7-8bad-4015a90715a4.png)
as seen from the image above the contributors list does not show the listed contributors as before
(before it would show the names of people who added the most stuff into the queue)

**Comment by airforce270** [comment]
Fixed by commits in #42

**Comment by papertek** [comment]
> Fixed by commits in #42

closed
