### ISSUE TITLE
Fix background not flashing when using easter egg functions

### ISSUE THREAD

**Issue by papertek** [papertek/CyDJ#41]
This is a CSS related issue but I believe it can be bypassed using the javascript. when I was making changes to the new page design i used `#mainpage` and `#wrap` in CSS instead of using `.body` (because using `.body` didnt work for some reason, even when using `!important`).

@airforce270 ASSISTANCE PLS <333

[](https://cytu.be/r/testplacelilroc)

**Comment by papertek** [comment]
now if `.body` is fixed (somehow) i dont need to rely `#mainpage` and `#wrap` for colors, this also fixes another bug involving the easter egg and party button

**Comment by airforce270** [comment]
Fixed by commit in #42
