### ISSUE TITLE
Change icons to look more modern

### ISSUE THREAD

**Issue by papertek** [papertek/CyDJ#43]
~~I was thinking of using Aller for CyDJ logo and maybe for the majority of the default fonts.~~
**Font has already been implemented and it's better than Aller lol**
~~Aller can be found here:~~
~~[https://www.fontsquirrel.com/fonts/aller](https://www.fontsquirrel.com/fonts/aller)~~

I was also thinking of using Font Awesome for the little icons on the screen. It can be found here (linked a tutorial):
[https://fontawesome.com/v5.15/how-to-use/javascript-api/setup/importing-icons](https://fontawesome.com/v5.15/how-to-use/javascript-api/setup/importing-icons)

Now just FYI, I don't know if this is even possible because of the script itself (server-sided, importing, etc). But please tell me if this is possible or not lol, I don't want to dig more into this then find out it's not possible once we are getting started. (the visualizer incident)

@airforce270

**Comment by airforce270** [comment]
Fonts are possible if they're loaded with a <link> tag from somewhere like google fonts: https://fonts.google.com/share?selection.family=Fira%20Sans:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700

Font Awesome is possible but would require us running something like webpack to compile and bundle to a single js file. Which we should do, but probably can wait until after this release

**Comment by papertek** [comment]
> 

Would rather just wait until everything else is finished then move onto this

**Comment by airforce270** [comment]
![](https://static-cdn.jtvnw.net/emoticons/v2/64138/static/light/3.0)

**Comment by papertek** [comment]
closing this for now, might revisit but it's not likely
