### ISSUE TITLE
Fix fullscreen button not working correctly

### ISSUE THREAD

**Issue by papertek** [papertek/CyDJ#46]
lol wtf
![image](https://user-images.githubusercontent.com/72106503/149645051-151897e7-4f79-4660-95d6-36100751734c.png)

as seen from the image above when pressing the fullscreen button located at the bottom of the player
![image](https://user-images.githubusercontent.com/72106503/149645145-f4a1cb81-41bd-452e-a5a4-690ad11db3ad.png)

**Comment by airforce270** [comment]
I don't see any references to fullscreening or the fullscreen button in the code.

@papertek does it work correctly in a plain cytube room?

Seems like the embedded fullscreen button (yt player / native player) still works as expected, which is a workaround for now

**Comment by papertek** [comment]
@airforce270 yes, it works correctly in a plain cytube room. just not in the main room (just found out 😞 )
