### ISSUE TITLE
PauseChamp mods make it so dj bot songs stay at the bottom of q so anybody can q above them

### ISSUE THREAD

**Issue by Alyjiahf** [papertek/CyDJ#48]
https://cdn.discordapp.com/attachments/482748530834800641/932891451724013619/Clueless3x.png

**Comment by papertek** [comment]
This is not the right repository and this is not the correct format. Please reread the Information dropdown for what you're looking for. (I think you're referring to the bot so here's the link to that [https://github.com/airforce270/CytubeBot](url))

**Comment by Xsogon** [comment]
have bot move user queued songs above?

**Comment by papertek** [comment]
> 

Again this is the wrong repository. You're looking for this one `https://github.com/airforce270/CyDJ/CytubeBot`
