### ISSUE TITLE
Fix party/easter egg spam

### ISSUE THREAD

**Issue by airforce270** [papertek/CyDJ#7]
Fix background changes not stopping when function is spammed (spam clicking party button and easter egg)

**Comment by airforce270** [comment]
I don't quite understand what needs to be done here

**Comment by papertek** [comment]
> I don't quite understand what needs to be done here

To reproduce it you need to spam click the party button, when you do that the background changes for `.body` spazzes out and gives you elipesy. Since `.body` is blocked because I changed `#mainpage` and `#wrap` colors, you'll see a tiny bit of it to the right where the scroll bar is

**Comment by papertek** [comment]
This goes for for !inba command aswell

**Comment by airforce270** [comment]
Not going away after spam is now fixed. still blocked by color changes but this but itself is fixed
