### ISSUE TITLE
Fix images redirecting to MLP

### ISSUE THREAD

**Issue by papertek** [papertek/CyDJ#76]
![image](https://user-images.githubusercontent.com/72106503/152278535-551de7d7-516f-4b7b-9362-c41f689044f7.png)

as seen from the screenshot above all the images redirect to MLP

im not a brony

**Comment by airforce270** [comment]
> im not a brony

![](https://cdn.betterttv.net/emote/6041012b306b602acc596ddc/2x.gif)
